import type { Theme } from "~/types/theme";

export const THEMES = [
  {
    id: "classic",
    name: "Classic",
    colors: {
      primary: "#fff",
      primaryOffset: "#f7f7f9",
      secondary: "#373a3c",
      secondaryOffset: "#818a91",
      tertiary: "#ff335f",
      tertiaryOffset: "#ff1447",
      quaternary: "#43a9a3",
      quinary: "#dadcde",
    },
    isDarkType: false,
  },
  {
    id: "dark",
    name: "Dark",
    colors: {
      primary: "#0e141b",
      primaryOffset: "#252526",
      secondary: "#fff",
      secondaryOffset: "#818a91",
      tertiary: "#ff5277",
      tertiaryOffset: "#ff2957",
      quaternary: "#43a9a3",
      quinary: "#393838",
    },
    isDarkType: true,
  },
  {
    id: "koopa",
    name: "Koopa Beach",
    colors: {
      primary: "#fffffe",
      primaryOffset: "#e3f6f5",
      secondary: "#272343",
      secondaryOffset: "#4c567d",
      tertiary: "#ff9d00",
      tertiaryOffset: "#ffca00",
      quaternary: "#bae8e8",
      quinary: "#bcd6d6",
    },
    isDarkType: false,
  },
  {
    id: "choco",
    name: "Choco Mountain",
    colors: {
      primary: "#55423d",
      primaryOffset: "#41312E",
      secondary: "#fffffe",
      secondaryOffset: "#ffc0ad",
      tertiary: "#f3ab87",
      tertiaryOffset: "#ffc0ad",
      quaternary: "#e78fb3",
      quinary: "#271c19",
    },
    isDarkType: true,
  },
  {
    id: "moomoo",
    name: "Moo Moo Farm",
    colors: {
      primary: "#fef6e4",
      primaryOffset: "#f3e1d8",
      secondary: "#172c66",
      secondaryOffset: "#006e8a",
      tertiary: "#f582ae",
      tertiaryOffset: "#ff3d6a",
      quaternary: "#8bd3dd",
      quinary: "#e0c1b1",
    },
    isDarkType: false,
  },
  {
    id: "bowser",
    name: "Bowser's Castle",
    colors: {
      primary: "#16161a",
      primaryOffset: "#29293e",
      secondary: "#fffffe",
      secondaryOffset: "#94a1b2",
      tertiary: "#7f5af0",
      tertiaryOffset: "#e068fd",
      quaternary: "#2cb67d",
      quinary: "#383a61",
    },
    isDarkType: true,
  },
  {
    id: "yoshi",
    name: "Yoshi Valley",
    colors: {
      primary: "#fafbf5",
      primaryOffset: "#f2ede9",
      secondary: "#41474C",
      secondaryOffset: "#757D84",
      tertiary: "#99C221",
      tertiaryOffset: "#6E910A",
      quaternary: "#E55812",
      quinary: "#cec6be",
    },
    isDarkType: false,
  },
  {
    id: "rainbow",
    name: "Rainbow Road",
    colors: {
      primary: "#140527",
      primaryOffset: "#311b46",
      secondary: "#feff00",
      secondaryOffset: "#ff464d",
      tertiary: "#49f5f7",
      tertiaryOffset: "#5dccf8",
      quaternary: "#01c317",
      quinary: "#d846ff",
    },
    isDarkType: true,
  },
  {
    id: "lobster",
    name: "Lobster Life",
    colors: {
      primary: "#fcddd4",
      primaryOffset: "#ffb9ad",
      secondary: "#4b1313",
      secondaryOffset: "#146caa",
      tertiary: "#b62b2b",
      tertiaryOffset: "#FF0030",
      quaternary: "#fb9f13",
      quinary: "#f1797c",
    },
    isDarkType: false,
  },
  {
    id: "hacker",
    name: "Hacker News",
    colors: {
      primary: "#F6F6EF",
      primaryOffset: "#F8F8EC",
      secondary: "#000000",
      secondaryOffset: "#828282",
      tertiary: "#FF6600",
      tertiaryOffset: "#F56200",
      quaternary: "#FF6600",
      quinary: "#FF6600",
    },
    isDarkType: false,
  },
] satisfies Theme[];
